index.html, static/css/style.css, static/js/index.js
I added an index.html page, added the static folder with css and js files, and also tested that everything is working as intended.
=> add basic html, css, bootstrap and place files in their respective folders.

index.html, static/css/style.css, static/js/index.js
Created and added a basic landing page to test deployment.
=> feat: Create a basic landing page

index.html, static/css/style.css, static/js/index.js
=> chore: refine html structure for header, main, footer

index.html, static/css/style.css
=> Add styles to button for user feedback, minor typo corrections

index.html
=> chore: reroute index.html link to avoid redundancy

README.md
=> docs: edit read me for contributing member

index.html, static/css/style.css
=> Add styles to questions and buttons

404.html, static/css/style.css
=> Clarity for error 404 page

404.html
=> Edit 404 page

README.md
Add UX and user stories, created and linked TESTING.md to README.md
=> Add UX to TESTING.md & include a TESTING.md

static/css/style.css
=> add global colors

static/css/style.css
=> Adjust color for accessibility criteria

404.html
=> Remove start new trivia button from error 404 page

404.html
=> Add heading and reference to home link on error 404 page

static/css/style.css
=> Adjust quiz buttons for varying question lengths

TESTING.md
=> Modify testing results for the current build

static/css/style.css
=> adjust modal design

static/css/style.css
=> remove unused root variables

README.md, TESTING.md
Add about page to TESTING.md and fixed typo in README.md
=> Add about page to TESTING.md

README.md
=> add credit to readme

static/css/style.css
=> remove root variables in css

about.html
Remove link in menu for about page on about page
=> Remove link in menu for about page on about page

static/css/style.css
=> Style adjustment to nav menu and intro text

404.html
=> Adjust navigation menu list on error 404 page

505.html
=> adjust navigation menu list on error 505 page

static/css/style.css
=> edit sound button
